server:
  port: 8080
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    servlet:
      multipart:
        #单个文件最大尺寸
        max-file-size: 10mb
        #一次请求最大尺寸
        max-request-size: 50mb
    thymeleaf:
      check-template: true
      check-template-location: true
      mode: HTML
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.me.model
mapper:
  mappers: com.me.dao
  not-empty: false
  identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
    file: myLog.log